### ISSUE TITLE
Thermostat supports climate.turn_off service but not climate.turn_on?

### ISSUE THREAD

**Issue by andrew-kennedy** [swingerman/ha-dual-smart-thermostat#133]
I noticed after I most updated the other day to the most recent version through HACS, my dual smart thermostat I set up no longer supports `climate.turn_on`, which means I can no longer turn it on through google assistant. Is this intentional?

```
2024-03-21 03:33:06.639 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.turn_on (c:01HSG94NAEVQGFEX283BTMTDAZ): entity_id=['climate.eight_sleep_thermostat']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2335, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 887, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity climate.eight_sleep_thermostat does not support this service.
```

**Comment by swingerman** [comment]
Please check [v0.9.5-beta.2](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.5-beta.2)
