### ISSUE TITLE
[feat] validate preset modes by target temperatures  Failed to call service climate/set_preset_mode...

### ISSUE THREAD

**Issue by mihailmoise** [swingerman/ha-dual-smart-thermostat#172]
Hi,

I use dual smart thermostat with both heat and cool, and 1 sensor. Config:

```
climate:
  - platform: dual_smart_thermostat
    name: Living room dual thermostat
    heater: switch.centrala_termica
    cooler: climate.c652fde2
    target_sensor: sensor.senzor_temperatura_living_temperature
    min_temp: 10
    max_temp: 28
    ac_mode: false
    target_temp: 17
    target_temp_high: 23
    target_temp_low: 22
    cold_tolerance: 0.5
    hot_tolerance: 0.4
    min_cycle_duration:
      seconds: 60
    initial_hvac_mode: "heat" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 14
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 22.5
    comfort:
      temperature: 21
    sleep:
      temperature: 21
    precision: 0.1
    target_temp_step: 0.5
```

Card config is:

    - type: thermostat
      entity: climate.living_room_dual_thermostat
      show_current_as_primary: true
      features:
        - style: icons
          preset_modes:
            - none
            - away
            - home
            - comfort
            - sleep
          type: climate-preset-modes
        - type: climate-hvac-modes
          hvac_modes:
            - 'off'
            - heat
            - cool
            - heat_cool
      name: ' '

There is an issue when I'm trying to set Comfort or Home or Sleep modes, with UI error: "Failed to call service climate/set_preset_mode. 'home'". Other available and working modes: None, Away.
Issue manifests on any hvac modes.
Dual Smart Thermostat installed and used since Jan '24.

<img width="188" alt="image" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/3167960/84c7455e-c246-4c4c-8a95-faeea9436c83">

System / Log message is always about 'home' no matter which other non-working option I select:

```
Log details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: April 22, 2024 at 9:04:07 AM (27 occurrences)
Last logged: 10:08:18 AM

[547542889536] 'home'
[547542889536] 'sleep'
[547801151168] 'comfort'
[547801151168] 'home'
[547801151168] 'sleep'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 769, in async_handle_set_preset_mode_service
    await self.async_set_preset_mode(preset_mode)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 809, in async_set_preset_mode
    self.presets.set_preset_mode(preset_mode)
  File "/config/custom_components/dual_smart_thermostat/managers/preset_manager.py", line 130, in set_preset_mode
    self._set_presets_when_have_preset_mode(preset_mode)
  File "/config/custom_components/dual_smart_thermostat/managers/preset_manager.py", line 157, in _set_presets_when_have_preset_mode
    self._temperatures.target_temp_low = self._presets_range[preset_mode][0]
                                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'home'
```

HA version: 
```
Core 2024.4.3
Supervisor 2024.04.0
Operating System 12.2
Frontend 20240404.2
```

Dual Smart Thermostat version: 0.9.5

Thanks,
Mihail

**Comment by swingerman** [comment]
Thanks for finding this. For now, please try to set all target temperatures for all presets as it's the only way it works at this point.
I will work on a more flexible solution.

**Comment by mihailmoise** [comment]
Thanks, setting target temperatures low and high made the thing work again.
