### ISSUE TITLE
[BUG] Component won't run on Core v2024.3.1 - config warns about exception

### ISSUE THREAD

**Issue by smnfv** [swingerman/ha-dual-smart-thermostat#213]
Hi" I'm using the docker based versione of Home Assistant and have installed the custom component via HACS.

I'm running into this issue: After setting up a minimal configuration in configuration.yaml, I get the following warning when validating config:

> Platform error 'climate' from integration 'dual_smart_thermostat' - Exception importing custom_components.dual_smart_thermostat.climate

Checking the logs yields the following stack trace:

```python
Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1025, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 338, in <module>
    class DualSmartThermostat(ClimateEntity, RestoreEntity):
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 899, in DualSmartThermostat
    self, event: Event[EventStateChangedData]
                 ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'Event' is not subscriptable
``` 

Relevant config is as follows:

```python
climate:
  - platform: generic_thermostat
    unique_id: climate.termostato
    name: Termostato Test
    heater: switch.termostato
    target_sensor: sensor.termostato_temperature
  - platform: dual_smart_thermostat
    name: Termostato Dual
    heater: switch.switch
    target_sensor: sensor.termostato_temperature
```

Please do forgive me if something is missing, this is my first time opening an issue.

**Comment by swingerman** [comment]
The required version was wrongly set to 2024.2 in the component.
The current version should run well on v2024.4.2. Please give it a try.

**Comment by smnfv** [comment]
Can confirm updating solved the issue. Thank you.
